const ALLOWED_ORIGINS=new Set(['https://21lalit.github.io','http://localhost:8000','http://127.0.0.1:8000']);
function cors(request){const origin=request.headers.get('Origin')||'';return{'Access-Control-Allow-Origin':ALLOWED_ORIGINS.has(origin)?origin:'https://21lalit.github.io','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization','Vary':'Origin','Cache-Control':'no-store'}}
function json(data,status,request){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json',...cors(request)}})}
async function visitorId(request,secret){const ip=request.headers.get('CF-Connecting-IP')||'unknown',key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(ip)),hex=[...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,'0')).join('');return `NODE-${hex.slice(0,12).toUpperCase()}`}
function geo(request){const c=request.cf||{};return{country:c.country||'XX',region:c.region||'',city:c.city||'',latitude:c.latitude==null?null:Math.round(Number(c.latitude)*10)/10,longitude:c.longitude==null?null:Math.round(Number(c.longitude)*10)/10}}
async function upsertVisitor(env,id,g){const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO visitors(visitor_id,country,region,city,latitude,longitude,first_seen,last_seen,visit_count) VALUES(?,?,?,?,?,?,?,?,1) ON CONFLICT(visitor_id) DO UPDATE SET last_seen=excluded.last_seen,visit_count=visit_count+1,country=excluded.country,region=excluded.region,city=excluded.city,latitude=excluded.latitude,longitude=excluded.longitude`).bind(id,g.country,g.region,g.city,g.latitude,g.longitude,now,now).run()}
async function hmac(value,secret){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value));return btoa(String.fromCharCode(...new Uint8Array(sig))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function same(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
async function issueSession(env){const payload=btoa(JSON.stringify({role:'admin',exp:Date.now()+30*60*1000})).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''),signature=await hmac(payload,env.ADMIN_SESSION_SECRET);return `${payload}.${signature}`}
async function isAdmin(request,env){const token=(request.headers.get('Authorization')||'').replace(/^Bearer\s+/,'');if(!token.includes('.'))return false;const [payload,signature]=token.split('.');if(!same(signature,await hmac(payload,env.ADMIN_SESSION_SECRET)))return false;try{return JSON.parse(atob(payload.replaceAll('-','+').replaceAll('_','/'))).exp>Date.now()}catch{return false}}
export default{async fetch(request,env){
 const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors(request)});
 if(!ALLOWED_ORIGINS.has(request.headers.get('Origin')||'')&&!url.pathname.endsWith('/health'))return json({error:'origin_not_allowed'},403,request);
 try{
  if(url.pathname==='/api/health')return json({status:'ok',privacy:'pseudonymous_ip_hmac'},200,request);
  const id=await visitorId(request,env.IP_HASH_SECRET),g=geo(request);
  if(url.pathname==='/api/admin/login'&&request.method==='POST'){const prior=await env.DB.prepare("SELECT failures,last_attempt FROM admin_attempts WHERE visitor_id=?").bind(id).first();if(prior?.failures>=5&&Date.now()-Date.parse(prior.last_attempt)<15*60*1000)return json({error:'temporarily_locked'},429,request);const b=await request.json();if(!same(String(b.username||''),env.ADMIN_USERNAME)||!same(String(b.password||''),env.ADMIN_PASSWORD)){await env.DB.prepare("INSERT INTO admin_attempts(visitor_id,failures,last_attempt) VALUES(?,1,?) ON CONFLICT(visitor_id) DO UPDATE SET failures=failures+1,last_attempt=excluded.last_attempt").bind(id,new Date().toISOString()).run();return json({error:'invalid_credentials'},401,request)}await env.DB.prepare('DELETE FROM admin_attempts WHERE visitor_id=?').bind(id).run();return json({token:await issueSession(env),expires_in:1800},200,request)}
  if(url.pathname==='/api/admin/stats'&&request.method==='GET'){if(!await isAdmin(request,env))return json({error:'admin_required'},401,request);const stats=await env.DB.prepare('SELECT (SELECT COUNT(*) FROM visitors) visitors,(SELECT COUNT(*) FROM threat_events) events,(SELECT COUNT(*) FROM threat_events WHERE risk>=80) critical,(SELECT MAX(created_at) FROM threat_events) latest_event').first();return json({stats},200,request)}
  if(url.pathname==='/api/admin/reset'&&request.method==='POST'){if(!await isAdmin(request,env))return json({error:'admin_required'},401,request);await env.DB.batch([env.DB.prepare('DELETE FROM threat_events'),env.DB.prepare('DELETE FROM visitors'),env.DB.prepare('DELETE FROM admin_attempts')]);return json({reset:true,at:new Date().toISOString()},200,request)}
  if(url.pathname==='/api/visit'&&request.method==='POST'){await upsertVisitor(env,id,g);await env.DB.batch([env.DB.prepare("DELETE FROM threat_events WHERE created_at < datetime('now','-30 days')"),env.DB.prepare("DELETE FROM visitors WHERE last_seen < datetime('now','-30 days') AND visitor_id NOT IN (SELECT visitor_id FROM threat_events)")]);const row=await env.DB.prepare('SELECT visitor_id,country,region,city,latitude,longitude,first_seen,last_seen,visit_count FROM visitors WHERE visitor_id=?').bind(id).first();return json({visitor:row,client_ip:request.headers.get('CF-Connecting-IP')||'',retention_days:30},200,request)}
  if(url.pathname==='/api/events'&&request.method==='POST'){await upsertVisitor(env,id,g);const b=await request.json(),allowed=['event_id','attack','family','risk','action','outcome','source_label','target_label'];if(!b.event_id||!b.attack||!Number.isFinite(Number(b.risk)))return json({error:'invalid_event'},422,request);await env.DB.prepare(`INSERT OR IGNORE INTO threat_events(visitor_id,event_id,created_at,attack,family,risk,action,outcome,source_label,target_label) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(id,String(b.event_id).slice(0,64),new Date().toISOString(),String(b.attack).slice(0,80),String(b.family||'Unknown').slice(0,50),Math.max(0,Math.min(100,Number(b.risk))),String(b.action||'observe').slice(0,40),String(b.outcome||'simulated').slice(0,40),String(b.source_label||'').slice(0,45),String(b.target_label||'').slice(0,45)).run();return json({recorded:true,visitor_id:id},201,request)}
  if(url.pathname==='/api/intel'&&request.method==='GET'){const nodes=await env.DB.prepare(`SELECT v.visitor_id,v.country,v.region,v.city,v.latitude,v.longitude,v.first_seen,v.last_seen,v.visit_count,COUNT(e.id) event_count,COALESCE(MAX(e.risk),0) max_risk FROM visitors v LEFT JOIN threat_events e ON e.visitor_id=v.visitor_id GROUP BY v.visitor_id ORDER BY v.last_seen DESC LIMIT 100`).all(),events=await env.DB.prepare(`SELECT e.event_id,e.visitor_id,e.created_at,e.attack,e.family,e.risk,e.action,e.outcome,v.country,v.region FROM threat_events e JOIN visitors v ON v.visitor_id=e.visitor_id ORDER BY e.created_at DESC LIMIT 100`).all();return json({nodes:nodes.results,events:events.results,privacy:{raw_ip_stored:false,coordinates_rounded:true}},200,request)}
  return json({error:'not_found'},404,request);
 }catch(error){return json({error:'service_error',detail:error.message},500,request)}
}};
