const ALLOWED_ORIGINS=new Set(['https://21lalit.github.io','https://clads-intel.clads-defense.workers.dev','http://localhost:8000','http://127.0.0.1:8000']);
function cors(request){const origin=request.headers.get('Origin')||'';return{'Access-Control-Allow-Origin':ALLOWED_ORIGINS.has(origin)?origin:'https://21lalit.github.io','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization','Vary':'Origin','Cache-Control':'no-store'}}
function json(data,status,request){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json',...cors(request)}})}
function blockedPage(block){const until=Date.parse(block.expires_at);return new Response(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Access temporarily restricted · CLADS</title><style>*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at 80% 10%,#301b64,transparent 35%),#070817;color:#f4f7ff;font:15px Inter,system-ui}.box{width:min(560px,calc(100% - 32px));padding:42px;border:1px solid #663f91;border-radius:24px;background:linear-gradient(145deg,#171332,#0b0c20);box-shadow:0 25px 80px #0008}.icon{width:64px;height:64px;display:grid;place-items:center;border-radius:18px;background:#ff5f7e18;border:1px solid #ff5f7e;color:#ff7890;font-size:28px}small{color:#67f7d4;letter-spacing:.14em}h1{font-size:38px;margin:20px 0 10px}p{color:#9da8ca}.timer{font:700 38px monospace;color:#62c7ff;margin:28px 0}button{border:0;border-radius:12px;padding:13px 18px;background:linear-gradient(100deg,#67f7d4,#62c7ff,#9d78ff);font-weight:800;cursor:pointer}</style></head><body><main class="box"><div class="icon">⛨</div><small>CLADS EDGE PROTECTION</small><h1>Access temporarily restricted</h1><p>Your recent activity exceeded the active security threshold. Access will restore automatically after the cooling period.</p><div id="timer" class="timer">05:00</div><p>Reason: ${String(block.reason).replace(/[<>&"]/g,'')}</p><button onclick="location.reload()">CHECK ACCESS</button></main><script>const end=${until};function tick(){const s=Math.max(0,Math.ceil((end-Date.now())/1000)),m=String(Math.floor(s/60)).padStart(2,'0'),r=String(s%60).padStart(2,'0');document.getElementById('timer').textContent=m+':'+r;if(!s)location.reload()}tick();setInterval(tick,1000)</script></body></html>`,{status:403,headers:{'Content-Type':'text/html;charset=UTF-8','Cache-Control':'no-store'}})}
async function visitorId(request,secret){const ip=request.headers.get('CF-Connecting-IP')||'unknown',key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(ip)),hex=[...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,'0')).join('');return `NODE-${hex.slice(0,12).toUpperCase()}`}
function geo(request){const c=request.cf||{};return{country:c.country||'XX',region:c.region||'',city:c.city||'',latitude:c.latitude==null?null:Math.round(Number(c.latitude)*10)/10,longitude:c.longitude==null?null:Math.round(Number(c.longitude)*10)/10}}
async function upsertVisitor(env,id,g){const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO visitors(visitor_id,country,region,city,latitude,longitude,first_seen,last_seen,visit_count) VALUES(?,?,?,?,?,?,?,?,1) ON CONFLICT(visitor_id) DO UPDATE SET last_seen=excluded.last_seen,visit_count=visit_count+1,country=excluded.country,region=excluded.region,city=excluded.city,latitude=excluded.latitude,longitude=excluded.longitude`).bind(id,g.country,g.region,g.city,g.latitude,g.longitude,now,now).run()}
async function hmac(value,secret){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value));return btoa(String.fromCharCode(...new Uint8Array(sig))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function same(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
async function issueSession(env){const payload=btoa(JSON.stringify({role:'admin',exp:Date.now()+30*60*1000})).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''),signature=await hmac(payload,env.ADMIN_SESSION_SECRET);return `${payload}.${signature}`}
async function isAdmin(request,env){const token=(request.headers.get('Authorization')||'').replace(/^Bearer\s+/,'');if(!token.includes('.'))return false;const [payload,signature]=token.split('.');if(!same(signature,await hmac(payload,env.ADMIN_SESSION_SECRET)))return false;try{return JSON.parse(atob(payload.replaceAll('-','+').replaceAll('_','/'))).exp>Date.now()}catch{return false}}
export default{async fetch(request,env){
 const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors(request)});
 const origin=request.headers.get('Origin')||'';if(url.pathname.startsWith('/api/')&&origin&&!ALLOWED_ORIGINS.has(origin)&&!url.pathname.endsWith('/health'))return json({error:'origin_not_allowed'},403,request);
 try{
  if(url.pathname==='/api/health')return json({status:'ok',privacy:'pseudonymous_ip_hmac'},200,request);
  const id=await visitorId(request,env.IP_HASH_SECRET),g=geo(request);
  await env.DB.batch([env.DB.prepare("UPDATE enforcement_history SET released_at=datetime('now'),release_type='automatic' WHERE released_at IS NULL AND expires_at<=datetime('now')"),env.DB.prepare("DELETE FROM access_blocks WHERE expires_at <= datetime('now')")]);
  if(url.pathname==='/api/admin/login'&&request.method==='POST'){const prior=await env.DB.prepare("SELECT failures,last_attempt FROM admin_attempts WHERE visitor_id=?").bind(id).first();if(prior?.failures>=5&&Date.now()-Date.parse(prior.last_attempt)<15*60*1000)return json({error:'temporarily_locked'},429,request);const b=await request.json();if(!same(String(b.username||''),env.ADMIN_USERNAME)||!same(String(b.password||''),env.ADMIN_PASSWORD)){await env.DB.prepare("INSERT INTO admin_attempts(visitor_id,failures,last_attempt) VALUES(?,1,?) ON CONFLICT(visitor_id) DO UPDATE SET failures=failures+1,last_attempt=excluded.last_attempt").bind(id,new Date().toISOString()).run();return json({error:'invalid_credentials'},401,request)}await env.DB.prepare('DELETE FROM admin_attempts WHERE visitor_id=?').bind(id).run();return json({token:await issueSession(env),expires_in:1800},200,request)}
  if(url.pathname==='/api/admin/stats'&&request.method==='GET'){if(!await isAdmin(request,env))return json({error:'admin_required'},401,request);const stats=await env.DB.prepare("SELECT (SELECT COUNT(*) FROM visitors) visitors,(SELECT COUNT(*) FROM threat_events) events,(SELECT COUNT(*) FROM threat_events WHERE risk>=80) critical,(SELECT COUNT(*) FROM access_blocks WHERE expires_at>datetime('now')) active_blocks,(SELECT COUNT(*) FROM enforcement_history) lifetime_blocks,(SELECT MAX(created_at) FROM threat_events) latest_event").first();return json({stats},200,request)}
  if(url.pathname==='/api/admin/blocks'&&request.method==='GET'){if(!await isAdmin(request,env))return json({error:'admin_required'},401,request);const rows=await env.DB.prepare("SELECT b.visitor_id,b.blocked_at,b.expires_at,b.reason,b.trigger_event_id,v.country,v.region FROM access_blocks b LEFT JOIN visitors v ON v.visitor_id=b.visitor_id WHERE b.expires_at>datetime('now') ORDER BY b.expires_at DESC").all();return json({blocks:rows.results},200,request)}
  if(url.pathname.startsWith('/api/admin/blocks/')&&request.method==='DELETE'){if(!await isAdmin(request,env))return json({error:'admin_required'},401,request);const node=decodeURIComponent(url.pathname.split('/').pop());await env.DB.batch([env.DB.prepare("UPDATE enforcement_history SET released_at=datetime('now'),release_type='admin' WHERE visitor_id=? AND released_at IS NULL").bind(node),env.DB.prepare('DELETE FROM access_blocks WHERE visitor_id=?').bind(node)]);return json({unblocked:true,visitor_id:node},200,request)}
  if(url.pathname==='/api/admin/reset'&&request.method==='POST'){if(!await isAdmin(request,env))return json({error:'admin_required'},401,request);await env.DB.batch([env.DB.prepare('DELETE FROM threat_events'),env.DB.prepare('DELETE FROM visitors'),env.DB.prepare('DELETE FROM admin_attempts'),env.DB.prepare('DELETE FROM access_blocks'),env.DB.prepare('DELETE FROM enforcement_history')]);return json({reset:true,at:new Date().toISOString()},200,request)}
  const block=await env.DB.prepare("SELECT visitor_id,expires_at,reason FROM access_blocks WHERE visitor_id=? AND expires_at>datetime('now')").bind(id).first();if(block){if(url.pathname.startsWith('/api/'))return json({error:'temporarily_blocked',blocked_until:block.expires_at,reason:block.reason},403,request);return blockedPage(block)}
  if(url.pathname==='/api/visit'&&request.method==='POST'){await upsertVisitor(env,id,g);await env.DB.batch([env.DB.prepare("DELETE FROM threat_events WHERE created_at < datetime('now','-30 days')"),env.DB.prepare("DELETE FROM enforcement_history WHERE blocked_at < datetime('now','-30 days')"),env.DB.prepare("DELETE FROM visitors WHERE last_seen < datetime('now','-30 days') AND visitor_id NOT IN (SELECT visitor_id FROM threat_events)")]);const row=await env.DB.prepare("SELECT v.visitor_id,v.country,v.region,v.city,v.latitude,v.longitude,v.first_seen,v.last_seen,v.visit_count,(SELECT COUNT(*) FROM threat_events e WHERE e.visitor_id=v.visitor_id) event_count,(SELECT COUNT(*) FROM enforcement_history h WHERE h.visitor_id=v.visitor_id) block_count FROM visitors v WHERE v.visitor_id=?").bind(id).first();return json({visitor:row,client_ip:request.headers.get('CF-Connecting-IP')||'',retention_days:30},200,request)}
  if(url.pathname==='/api/events'&&request.method==='POST'){await upsertVisitor(env,id,g);const b=await request.json();if(!b.event_id||!b.attack||!Number.isFinite(Number(b.risk)))return json({error:'invalid_event'},422,request);const risk=Math.max(0,Math.min(100,Number(b.risk))),eventId=String(b.event_id).slice(0,64);await env.DB.prepare(`INSERT OR IGNORE INTO threat_events(visitor_id,event_id,created_at,attack,family,risk,action,outcome,source_label,target_label) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(id,eventId,new Date().toISOString(),String(b.attack).slice(0,80),String(b.family||'Unknown').slice(0,50),risk,String(b.action||'observe').slice(0,40),String(b.outcome||'evaluated').slice(0,40),String(b.source_label||'').slice(0,45),String(b.target_label||'').slice(0,45)).run();const recent=await env.DB.prepare("SELECT COUNT(*) count FROM threat_events WHERE visitor_id=? AND risk>=70 AND created_at>=datetime('now','-10 minutes')").bind(id).first();let blockedUntil=null;if(risk>=90||Number(recent.count)>=3){const reason=risk>=90?'Critical risk threshold exceeded':'Repeated high-risk activity';await env.DB.batch([env.DB.prepare("INSERT INTO access_blocks(visitor_id,blocked_at,expires_at,reason,trigger_event_id) VALUES(?,datetime('now'),datetime('now','+5 minutes'),?,?) ON CONFLICT(visitor_id) DO UPDATE SET blocked_at=excluded.blocked_at,expires_at=excluded.expires_at,reason=excluded.reason,trigger_event_id=excluded.trigger_event_id").bind(id,reason,eventId),env.DB.prepare("INSERT INTO enforcement_history(visitor_id,blocked_at,expires_at,reason,trigger_event_id) VALUES(?,datetime('now'),datetime('now','+5 minutes'),?,?)").bind(id,reason,eventId)]);const row=await env.DB.prepare('SELECT expires_at FROM access_blocks WHERE visitor_id=?').bind(id).first();blockedUntil=row.expires_at}return json({recorded:true,visitor_id:id,blocked_until:blockedUntil,history_retained:true},201,request)}
  if(url.pathname==='/api/intel'&&request.method==='GET'){const nodes=await env.DB.prepare(`SELECT v.visitor_id,v.country,v.region,v.city,v.latitude,v.longitude,v.first_seen,v.last_seen,v.visit_count,COUNT(DISTINCT e.id) event_count,COALESCE(MAX(e.risk),0) max_risk,(SELECT COUNT(*) FROM enforcement_history h WHERE h.visitor_id=v.visitor_id) block_count,(SELECT MAX(blocked_at) FROM enforcement_history h WHERE h.visitor_id=v.visitor_id) last_block_at FROM visitors v LEFT JOIN threat_events e ON e.visitor_id=v.visitor_id GROUP BY v.visitor_id ORDER BY v.last_seen DESC LIMIT 100`).all(),events=await env.DB.prepare(`SELECT e.event_id,e.visitor_id,e.created_at,e.attack,e.family,e.risk,e.action,e.outcome,v.country,v.region FROM threat_events e JOIN visitors v ON v.visitor_id=e.visitor_id ORDER BY e.created_at DESC LIMIT 100`).all();return json({nodes:nodes.results,events:events.results,privacy:{raw_ip_stored:false,coordinates_rounded:true},retention_days:30},200,request)}
  if(!url.pathname.startsWith('/api/')){const assetUrl=new URL(request.url);if(assetUrl.pathname==='/'||!assetUrl.pathname.split('/').pop().includes('.'))assetUrl.pathname='/index.html';return env.ASSETS.fetch(new Request(assetUrl,request))}return json({error:'not_found'},404,request);
 }catch(error){return json({error:'service_error',detail:error.message},500,request)}
}};
