const ALLOWED_ORIGINS=new Set(['https://21lalit.github.io','http://localhost:8000','http://127.0.0.1:8000']);
function cors(request){const origin=request.headers.get('Origin')||'';return{'Access-Control-Allow-Origin':ALLOWED_ORIGINS.has(origin)?origin:'https://21lalit.github.io','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Vary':'Origin','Cache-Control':'no-store'}}
function json(data,status,request){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json',...cors(request)}})}
async function visitorId(request,secret){const ip=request.headers.get('CF-Connecting-IP')||'unknown',key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(ip)),hex=[...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,'0')).join('');return `NODE-${hex.slice(0,12).toUpperCase()}`}
function geo(request){const c=request.cf||{};return{country:c.country||'XX',region:c.region||'',city:c.city||'',latitude:c.latitude==null?null:Math.round(Number(c.latitude)*10)/10,longitude:c.longitude==null?null:Math.round(Number(c.longitude)*10)/10}}
async function upsertVisitor(env,id,g){const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO visitors(visitor_id,country,region,city,latitude,longitude,first_seen,last_seen,visit_count) VALUES(?,?,?,?,?,?,?,?,1) ON CONFLICT(visitor_id) DO UPDATE SET last_seen=excluded.last_seen,visit_count=visit_count+1,country=excluded.country,region=excluded.region,city=excluded.city,latitude=excluded.latitude,longitude=excluded.longitude`).bind(id,g.country,g.region,g.city,g.latitude,g.longitude,now,now).run()}
export default{async fetch(request,env){
 const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors(request)});
 if(!ALLOWED_ORIGINS.has(request.headers.get('Origin')||'')&&!url.pathname.endsWith('/health'))return json({error:'origin_not_allowed'},403,request);
 try{
  if(url.pathname==='/api/health')return json({status:'ok',privacy:'pseudonymous_ip_hmac'},200,request);
  const id=await visitorId(request,env.IP_HASH_SECRET),g=geo(request);
  if(url.pathname==='/api/visit'&&request.method==='POST'){await upsertVisitor(env,id,g);await env.DB.batch([env.DB.prepare("DELETE FROM threat_events WHERE created_at < datetime('now','-30 days')"),env.DB.prepare("DELETE FROM visitors WHERE last_seen < datetime('now','-30 days') AND visitor_id NOT IN (SELECT visitor_id FROM threat_events)")]);const row=await env.DB.prepare('SELECT visitor_id,country,region,city,latitude,longitude,first_seen,last_seen,visit_count FROM visitors WHERE visitor_id=?').bind(id).first();return json({visitor:row,retention_days:30},200,request)}
  if(url.pathname==='/api/events'&&request.method==='POST'){await upsertVisitor(env,id,g);const b=await request.json(),allowed=['event_id','attack','family','risk','action','outcome','source_label','target_label'];if(!b.event_id||!b.attack||!Number.isFinite(Number(b.risk)))return json({error:'invalid_event'},422,request);await env.DB.prepare(`INSERT OR IGNORE INTO threat_events(visitor_id,event_id,created_at,attack,family,risk,action,outcome,source_label,target_label) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(id,String(b.event_id).slice(0,64),new Date().toISOString(),String(b.attack).slice(0,80),String(b.family||'Unknown').slice(0,50),Math.max(0,Math.min(100,Number(b.risk))),String(b.action||'observe').slice(0,40),String(b.outcome||'simulated').slice(0,40),String(b.source_label||'').slice(0,45),String(b.target_label||'').slice(0,45)).run();return json({recorded:true,visitor_id:id},201,request)}
  if(url.pathname==='/api/intel'&&request.method==='GET'){const nodes=await env.DB.prepare(`SELECT v.visitor_id,v.country,v.region,v.city,v.latitude,v.longitude,v.first_seen,v.last_seen,v.visit_count,COUNT(e.id) event_count,COALESCE(MAX(e.risk),0) max_risk FROM visitors v LEFT JOIN threat_events e ON e.visitor_id=v.visitor_id GROUP BY v.visitor_id ORDER BY v.last_seen DESC LIMIT 100`).all(),events=await env.DB.prepare(`SELECT e.event_id,e.visitor_id,e.created_at,e.attack,e.family,e.risk,e.action,e.outcome,v.country,v.region FROM threat_events e JOIN visitors v ON v.visitor_id=e.visitor_id ORDER BY e.created_at DESC LIMIT 100`).all();return json({nodes:nodes.results,events:events.results,privacy:{raw_ip_stored:false,coordinates_rounded:true}},200,request)}
  return json({error:'not_found'},404,request);
 }catch(error){return json({error:'service_error',detail:error.message},500,request)}
}};
